# Generated by Django 3.1.3 on 2021-04-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210416_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='comment',
            field=models.TextField(),
        ),
    ]
